/**
 * action types collection
 */

// splash.js Action types
const splashActionTypes = {
  LOAD_LOCAL_USER_SUCCESS: "LOAD_LOCAL_USER_SUCCESS",
  LOAD_LOCAL_USER_FAILED: "LOAD_LOCAL_USER_FAILED",
  CLEAN_LOCAL_USER: "CLEAN_LOCAL_USER",
  CHECK_APP_UPDATE: "CHECK_APP_UPDATE"
};

// login.js Aciton types
const loginActionTypes = {
  LOGIN_INIT: "LOGIN_INIT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED"
};

// appNavigator.js Action types
const navActionTypes = {
  SET_PAGE_RESULT: "SET_PAGE_RESULT",
  RESET_THIS_PAGE_TO: "RESET_THIS_PAGE_TO",
  NAV_REMOVE_PAGES_BETWEEN: "NAV_REMOVE_PAGES_BETWEEN",
  SUBSCRIPTION_PAGE_RESULT: "SUBSCRIPTION_PAGE_RESULT",
  CANCEL_SUBSCRIPTION_PAGE_RESULT: "CANCEL_SUBSCRIPTION_PAGE_RESULT"
};

// main.js Action types
const mainActionTypes = {
  SELECT_MAIN_TAB: "SELECT_MAIN_TAB"
};

// manual Action types
const manualActionTypes = {
  UPDATE_CAR_LICENSE: "UPDATE_CAR_LICENSE",
  SET_VISIBILITY_KEYBOARD: "SET_VISIBILITY_KEYBOARD",
  GET_PRE_LICENSE: "GET_PRE_LICENSE",
  MANUAL_START_RECEIVER_CAR_SUCCESS: "MANUAL_START_RECEIVER_CAR_SUCCESS",
  MANUAL_START_RECEIVER_CAR_FAILED: "MANUAL_START_RECEIVER_CAR_FAILED",
  MANUAL_QUERY_CAR_INFO_SUCCESS: "MANUAL_QUERY_CAR_INFO_SUCCESS",
  MANUAL_QUERY_CAR_INFO_FAILED: "MANUAL_QUERY_CAR_INFO_FAILED",
  VERIFY_QUERY_CAR_INFO_SUCCESS: "VERIFY_QUERY_CAR_INFO_SUCCESS",
  VERIFY_QUERY_CAR_INFO_FAILED: "VERIFY_QUERY_CAR_INFO_FAILED"
};

//receiveCar Action types
const receiveCarActionTypes = {
  GET_CAR_INFO_INIT: "GET_CAR_INFO_INIT",
  GET_CAR_INFO_SUCCESS: "GET_CAR_INFO_SUCCESS",
  GET_CAR_INFO_FAILED: "GET_CAR_INFO_FAILED",
  GET_CAR_RECOMMEND_INIT: "GET_CAR_RECOMMEND_INIT",
  GET_CAR_RECOMMEND_SUCCESS: "GET_CAR_RECOMMEND_SUCCESS",
  GET_CAR_INFO_SUCCESS_NO_DATA: "GET_CAR_INFO_SUCCESS_NO_DATA",
  GET_CAR_RECOMMEND_FAILED: "GET_CAR_RECOMMEND_FAILED",
  RECEIVE_CAR_INIT: "PICK_UP_CAR_INIT",
  RECEIVE_CAR_SUCCESS: "PICK_UP_CAR_SUCCESS",
  RECEIVE_CAR_FAILED: "PICK_UP_CAR_FAILED",
  UPLOAD_CAR_LICENSE_IMAGE_INIT: "UPLOAD_CAR_LICENSE_IMAGE_INIT",
  UPLOAD_CAR_LICENSE_IMAGE_SUCCESS: "UPLOAD_CAR_LICENSE_IMAGE_SUCCESS",
  UPLOAD_CAR_LICENSE_IMAGE_FAILED: "UPLOAD_CAR_LICENSE_IMAGE_FAILED",
  RECVICAR_IMAGE_INIT: "RECVICAR_IMAGE_INIT",
  RECVICAR_IMAGE_SUCCESS: "RECVICAR_IMAGE_SUCCESS",
  RECVICAR_IMAGE_FAILED: "RECVICAR_IMAGE_FAILED",
  VIN_CAR_TYPE_SUCCESS: "VIN_CAR_TYPE_SUCCESS",
  VIN_CAR_TYPE_FAILED: "VIN_CAR_TYPE_FAILED",
  MANUAL_START_RECEIVER_CAR_INIT: "MANUAL_START_RECEIVER_CAR_INIT",
  MANUAL_QUERY_CAR_INFO_INIT: "MANUAL_QUERY_CAR_INFO_INIT",
  RECVICAR_QUESTION_INIT: "RECVICAR_QUESTION_INIT",
  RECVICAR_QUESTION_SUCCESS: "RECVICAR_QUESTION_SUCCESS",
  RECVICAR_QUESTION_FAILED: "RECVICAR_QUESTION_FAILED",
  START_RECEIVER_CAR_INIT: "START_RECEIVER_CAR_INIT",
  VERIFY_QUERY_CAR_INFO_INIT: "VERIFY_QUERY_CAR_INFO_INIT",
  QUERY_UP_KEEP_INIT: "QUERY_UP_KEEP_INIT",
  QUERY_UP_KEEP_SUCCESS: "QUERY_UP_KEEP_SUCCESS",
  QUERY_UP_KEEP_FAILED: "QUERY_UP_KEEP_FAILED"
};

//autoTypeInput action types(选车牌)
const autoTypeInputActionTypes = {
  GET_CAR_BRAND_SUCCESS: "GET_CAR_BRAND_SUCCESS",
  GET_CAR_TYPE_SUCCESS: "GET_CAR_TYPE_SUCCESS",
  GET_QUERY_CAR_TYPE_SUCCESS: "GET_QUERY_CAR_TYPE_SUCCESS",
  GET_QUERY_CAR_TYPE_NO_DATA: "GET_QUERY_CAR_TYPE_NO_DATA",
  GET_CAR_BRAND_SUCCESS_NO_DATA: "GET_CAR_BRAND_SUCCESS_NO_DATA",
  GET_CHOOSE_CAR_TYPE_SUCCESS_NO_DATA: "GET_CHOOSE_CAR_TYPE_SUCCESS_NO_DATA",
  GET_CHOOSE_CAR_TYPE_FAILED: "GET_CHOOSE_CAR_TYPE_FAILED",
  GET_CHOOSE_CAR_SUCCESS_NO_DATA: "GET_CHOOSE_CAR_SUCCESS_NO_DATA",
  GET_QUERY_CAR_TYPE_FAILED: "GET_QUERY_CAR_TYPE_FAILED",
  GET_CHOOSE_CAR_FAILED: "GET_CHOOSE_CAR_FAILED",
  LOAD_AUTO_BRAND_SUCCESS: "LOAD_AUTO_BRAND_SUCCESS",
  LOAD_AUTO_MODEL: "LOAD_AUTO_MODEL",
  LOAD_AUTO_SPECS: "LOAD_AUTO_SPECS",
  AUTO_TYPE_INPUT: "AUTO_TYPE_INPUT",
  AUTO_TYPE_INPUT_UPDATE: "AUTO_TYPE_INPUT_UPDATE", //修改客户信息----选择车型
  LOAD_AUTO_BRAND: "LOAD_AUTO_BRAND",
  LOAD_AUTO_FAILED: "LOAD_AUTO_FAILED"
};

//board action types(车间看板)
const boardActionType = {
  GET_BOARD_INIT: "GET_BOARD_INIT",
  GET_BOARD_SUCCESS: "GET_BOARD_SUCCESS",
  GET_BOARD_NO_DATA: "GET_BOARD_NO_DATA",
  GET_BOARD_FAILED: "GET_BOARD_FAILED",

  END_BOARD_INIT: "END_BOARD_INIT",
  END_BOARD_SUCCESS: "END_BOARD_SUCCESS",
  END_BOARD_FAILED: "END_BOARD_FAILED",
  GET_JSON_INIT: "GET_JSON_INIT",
  GET_JSON_SUCCESS: "GET_JSON_SUCCESS",
  GET_JSON_FAILED: "GET_JSON_FAILED"
};

//support action types(保养手册)
const supportActionTypes = {
  GET_MILEAGE_SUCCESS: "GET_MILEAGE_SUCCESS",
  GET_PROJECT_SUCCESS: "GET_PROJECT_SUCCESS",
  GET_ONE_COLUMN_SUCCESS: "GET_ONE_COLUMN_SUCCESS",
  GET_SUPPORT_NO_DATA: "GET_SUPPORT_NO_DATA"
};

// carList action types(车辆相关)
const carActionTypes = {
  GET_CAR_LIST_INIT: "GET_CAR_LIST_INIT", //接车列表默认
  GET_CAR_LIST_SUCCESS: "GET_CAR_LIST_SUCCESS", //请求接车列表页数据成功
  GET_CAR_LIST_FAILED: "GET_CAR_LIST_FAILED", //请求接车列表页数据失败
  GET_CAR_REMAINS_INIT: "GET_CAR_REMAINS_INIT", //获取车辆遗留问题默认
  GET_CAR_REMAINS_SUCCESS: "GET_CAR_REMAINS_SUCCESS", //获取车辆遗留问题页数据成功
  GET_CAR_REMAINS_FAILED: "GET_CAR_REMAINS_FAILED", //获取车辆遗留问题页数据失败
  START_RECEIVER_CAR_SUCCESS: "START_RECEIVER_CAR_SUCCESS", //开始接车成功
  START_RECEIVER_CAR_FAILED: "START_RECEIVER_CAR_FAILED", //开始接车失败
  RECEIVE_MACHINE_OIL_SUCCESS: "RECEIVE_MACHINE_OIL_SUCCESS", //接车页获取机油推荐成功
  RECEIVE_MACHINE_OIL_FAILED: "RECEIVE_MACHINE_OIL_FAILED", //接车页获取机油推荐失败
  GET_CAR_DETAIL_INIT: "GET_CAR_DETAIL_INIT", //获取详情页车辆基本信息
  GET_CAR_DETAIL_SUCCESS: "GET_CAR_DETAIL_SUCCESS", //获取详情页车辆基本信息接口成功
  GET_CAR_DETAIL_FAILED: "GET_CAR_DETAIL_FAILED", //获取详情页车辆基本信息
  GET_CHECK_ID_DETAIL_INIT: "GET_CHECK_ID_DETAIL_INIT", //拿接车id获取checkID,默认
  GET_CHECK_ID_DETAIL_SUCCESS: "GET_CHECK_ID_DETAIL_SUCCESS", //拿接车id获取checkID,获取成功
  GET_CHECK_ID_DETAIL_FAILED: "GET_CHECK_ID_DETAIL_FAILED" //拿接车id获取checkID,获取失败
};
//录入报告
const entryReportActionTypes = {
  GET_REPORT_INFO_BY_CAR_INIT: "GET_REPORT_INFO_BY_CAR_INIT", //录入报告首页
  GET_REPORT_INFO_SUCCESS: "GET_REPORT_INFO_SUCCESS", //录入报告请求数据成功
  GET_REPORT_INFO_FAILED: "GET_REPORT_INFO_FAILED", //录入报告请求数据失败
  GET_CAR_PART_INIT: "GET_CAR_PART_INIT", //录入页面弹层
  GET_CAR_PART_INFO_SUCCESS: "GET_CAR_PART_INFO_SUCCESS", //录入弹层请求数据成功
  GET_CAR_PART_INFO_FAILED: "GET_CAR_PART_INFO_FAILED", //录入弹层请求数据失败
  GET_CAR_PART_SAVED_INIT: "GET_CAR_PART_SAVED_INIT", //修改了汽车部件弹层，传给后端保存
  GET_CAR_PART_SAVED_SUCCESS: "GET_CAR_PART_SAVED_SUCCESS", //修改了汽车部件弹层，传给后端保存成功
  GET_CAR_PART_SAVED_FAILED: "GET_CAR_PART_SAVED_FAILED", //修改了汽车部件弹层，传给后端保存失败,
  GET_CAR_PART_SAVED_NOOPERATE: "GET_CAR_PART_SAVED_NOOPERATE", //不能修改汽车部件弹层，传给后端保存失败,
  PUT_CAR_PART_IMG_INIT: "PUT_CAR_PART_IMG_INIT", //上传图片默认
  PUT_CAR_PART_IMG_SUCCESS: "PUT_CAR_PART_IMG_SUCCESS", //上传图片成功
  PUT_CAR_PART_IMG_FAILED: "PUT_CAR_PART_IMG_FAILED", //上传图片失败

  PUT_CAR_ADDPART_IMG_INIT: "PUT_CAR_ADDPART_IMG_INIT", //上传图片默认
  PUT_CAR_ADDPART_IMG_SUCCESS: "PUT_CAR_ADDPART_IMG_SUCCESS", //上传图片成功
  PUT_CAR_ADDPART_IMG_FAILED: "PUT_CAR_ADDPART_IMG_FAILED", //上传图片失败

  GET_CHECK_ID_INIT: "GET_CHECK_ID_INIT", //拿接车id获取checkID,默认
  GET_CHECK_ID_SUCCESS: "GET_CHECK_ID_SUCCESS", //拿接车id获取checkID,获取成功
  GET_CHECK_ID_FAILED: "GET_CHECK_ID_FAILED", //拿接车id获取checkID,获取失败
  PUT_REPORT_DATA_INIT: "PUT_REPORT_DATA_INIT", //拿接车id获取checkID,默认
  PUT_REPORT_DATA_SUCCESS: "PUT_REPORT_DATA_SUCCESS", //拿接车id获取checkID,获取成功
  PUT_REPORT_DATA_FAILED: "PUT_REPORT_DATA_FAILED", //拿接车id获取checkID,获取失败
  PUT_AUTO_COMPLETE_INIT: "PUT_AUTO_COMPLETE_INIT", //自动补全初始状态
  PUT_AUTO_COMPLETE_SUCCESS: "PUT_AUTO_COMPLETE_SUCCESS", //自动补全成功
  PUT_AUTO_COMPLETE_FAILED: "PUT_AUTO_COMPLETE_FAILED", //自动补全失败
  PUT_ADD_PARTS_INIT: "PUT_ADD_PARTS_INIT", //自定义故障默认
  PUT_ADD_PARTS_SUCCESS: "PUT_ADD_PARTS_SUCCESS", //自定义故障成功
  PUT_ADD_PARTS_FAILED: "PUT_ADD_PARTS_FAILED" //自定义故障失败
};
//获取车辆检测记录
const detectionActionTypes = {
  GET_CAR_DETECTION_INIT: "GET_CAR_DETECTION_INIT", //检测记录首页默认
  GET_CAR_DETECTION_SUCCESS: "GET_CAR_DETECTION_SUCCESS", //检测记录请求数据成功
  GET_CAR_DETECTION_FAILED: "GET_CAR_DETECTION_FAILED", //检测记录请求数据失败
  GET_CAR_DETECTION_DETAIL_INIT: "GET_CAR_DETECTION_DETAIL_INIT", //检测记录详情页默认
  GET_CAR_DETECTION_DETAIL_SUCCESS: "GET_CAR_DETECTION_DETAIL_SUCCESS", //检测记录详情页请求数据成功
  GET_CAR_DETECTION_DETAIL_FAILED: "GET_CAR_DETECTION_DETAIL_FAILED", //检测记录详情页请求数据失败
  GET_CAR_DETECTION_CHECK_INIT: "GET_CAR_DETECTION_CHECK_INIT", //拿接车id获取checkID,默认
  GET_CAR_DETECTION_CHECK_SUCCESS: "GET_CAR_DETECTION_CHECK_SUCCESS", //拿接车id获取checkID,获取成功
  GET_CAR_DETECTION_CHECK_FAILED: "GET_CAR_DETECTION_CHECK_FAILED", //拿接车id获取checkID,获取失败

  GET_CAR_DETECTION_MANUAL_INIT: "GET_CAR_DETECTION_MANUAL_INIT", //获取保养手册初始化
  GET_CAR_DETECTION_MANUAL_SUCCESS: "GET_CAR_DETECTION_MANUAL_SUCCESS", //获取保养手册成功
  GET_CAR_DETECTION_MANUAL_FAILED: "GET_CAR_DETECTION_MANUAL_FAILED" //获取保养手册失败
};
//获取车辆维保记录
const opportunityActionTypes = {
  GET_CAR_OPPORTUNITY_INIT: "GET_CAR_OPPORTUNITY_INIT", //维保记录首页默认
  GET_CAR_OPPORTUNITY_SUCCESS: "GET_CAR_OPPORTUNITY_SUCCESS", //维保记录请求数据成功
  GET_CAR_OPPORTUNITY_FAILED: "GET_CAR_OPPORTUNITY_FAILED" //维保记录请求数据失败
};
//确认施工
const constructionActionTypes = {
  GET_CONSTRUCTION_LIST_INIT: "GET_CONSTRUCTION_LIST_INIT", //确认施工页检测列表默认
  GET_CONSTRUCTION_LIST_SUCCESS: "GET_CONSTRUCTION_LIST_SUCCESS", //确认施工页检测列表成功
  GET_CONSTRUCTION_LIST_FAILED: "GET_CONSTRUCTION_LIST_FAILED", //确认施工页检测列表失败

  GET_CONSTRUCTION_MORE_INIT: "GET_CONSTRUCTION_MORE_INIT", //确认施工展示页默认状态
  GET_CONSTRUCTION_MORE_SUCCESS: "GET_CONSTRUCTION_MORE_SUCCESS", //确认施工展示页默认状态
  GET_CONSTRUCTION_MORE_FAILED: "GET_CONSTRUCTION_MORE_FAILED", //确认施工展示页默认状态

  PUT_BASIC_MAINTAIN_INIT: "PUT_BASIC_MAINTAIN_INIT", //确认施工基础信息修改后提交
  PUT_BASIC_MAINTAIN_SUCCESS: "PUT_BASIC_MAINTAIN_SUCCESS", //确认施工基础信息修改后提交成功
  PUT_BASIC_MAINTAIN_FAILED: "PUT_BASIC_MAINTAIN_FAILED", //确认施工基础信息修改后提交失败
  PUT_ADVICE_INIT: "PUT_ADVICE_INIT", //确认施工建议信息修改提交
  PUT_ADVICE_SUCCESS: "PUT_ADVICE_SUCCESS", //确认施工建议信息修改提交成功
  PUT_ADVICE_FAILED: "PUT_ADVICE_FAILED", //确认施工建议信息修改提交失败

  GET_SHARE_BINDUSER_INIT: "GET_SHARE_BINDUSER_INIT", //查询该车辆绑定的用户
  GET_SHARE_BINDUSER_SUCCESS: "GET_SHARE_BINDUSER_SUCCESS", //查询该车辆绑定的用户成功
  GET_SHARE_BINDUSER_FAILED: "GET_SHARE_BINDUSER_FAILED", //查询该车辆绑定的用户失败

  GET_SHARE_USER_INIT: "GET_SHARE_USER_INIT", //车辆绑定用户初始
  GET_SHARE_USER_SUCCESS: "GET_SHARE_USER_SUCCESS", //车辆绑定用户成功
  GET_SHARE_USER_FAILED: "GET_SHARE_USER_FAILED", //车辆绑定用户失败

  GET_TWO_CODE_TEXT_INIT: "GET_TWO_CODE_TEXT_INIT", //获取二维码字符文本初始
  GET_TWO_CODE_TEXT_SUCCESS: "GET_TWO_CODE_TEXT_SUCCESS", //获取二维码字符文本成功
  GET_TWO_CODE_TEXT_FAILED: "GET_TWO_CODE_TEXT_FAILED", //获取二维码字符文本失败

  GET_TWO_CODE_IMAGE_INIT: "GET_TWO_CODE_IMAGE_INIT", //获取二维码字符文本初始
  GET_TWO_CODE_IMAGE_SUCCESS: "GET_TWO_CODE_IMAGE_SUCCESS", //获取二维码字符文本成功
  GET_TWO_CODE_IMAGE_FAILED: "GET_TWO_CODE_IMAGE_FAILED", //获取二维码字符文本失败

  GET_OWER_CARS_INIT: "GET_OWER_CARS_INIT", //推送车主
  GET_OWER_CARS_SUCCESS: "GET_OWER_CARS_SUCCESS", //推送车主成功
  GET_OWER_CARS_FAILED: "GET_OWER_CARS_FAILED", //推送车主失败

  GET_MANUAL_INFO_INIT: "GET_MANUAL_INFO_INIT", //获取保养手册初始化
  GET_MANUAL_INFO_SUCCESS: "GET_MANUAL_INFO_SUCCESS", //获取保养手册成功
  GET_MANUAL_INFO_FAILED: "GET_MANUAL_INFO_FAILED", //获取保养手册失败

  GET_SENT_REPORT_STATIST_INIT: "GET_SENT_REPORT_STATIST_INIT", //发送报告统计初始化
  GET_SENT_REPORT_STATIST_SUCCESS: "GET_SENT_REPORT_STATIST_SUCCESS", //发送报告统计成功
  GET_SENT_REPORT_STATIST_FAILED: "GET_SENT_REPORT_STATIST_FAILED", //发送报告统计初失败

  GET_SEND_REPORT_INIT: "GET_SEND_REPORT_INIT", //获取保养手册初始化
  GET_SEND_REPORT_SUCCESS: "GET_SEND_REPORT_SUCCESS", //获取保养手册成功
  GET_SEND_REPORT_FAILED: "GET_SEND_REPORT_FAILED" //获取保养手册失败
};
//personCenter action types(个人中心)
const personCenterActionTypes = {
  USER_EXIT_INIT: "USER_EXIT_INIT",
  USER_EXIT_SUCCESS: "USER_EXIT_SUCCESS",
  USER_EXIT_FAILED: "USER_EXIT_FAILED",
  RESET_PASSWORD_INIT: "RESET_PASSWORD_INIT",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED",
  USER_REPORT_INIT: "USER_REPORT_INIT",
  USER_REPORT_SUCCESS: "USER_REPORT_SUCCESS",
  USER_REPORT_FAILED: "USER_REPORT_FAILED"
};

//feedBack action types(反馈信息)
const feedBackActionTypes = {
  FEEDBACK_IMG_INIT: "FEEDBACK_IMG_INIT",
  FEEDBACK_IMG_SUCCESS: "FEEDBACK_IMG_SUCCESS",
  FEEDBACK_IMG_FAILED: "FEEDBACK_IMG_FAILED",
  FEEDBACK_SUBMIT_INIT: "FEEDBACK_SUBMIT_INIT",
  FEEDBACK_SUBMIT_SUCCESS: "FEEDBACK_SUBMIT_SUCCESS",
  FEEDBACK_SUBMIT_FAILED: "FEEDBACK_SUBMIT_FAILED"
};
//maintenance booklet action (保养手册)
const MaintencanceBookletAction = {
  GET_MAINTENCANCE_BOOKLET: "GET_MAINTENCANCE_BOOKLET",
  GET_MAINTENCANCE_BOOKLET_SUCCESS: "GET_MAINTENCANCE_BOOKLET_SUCCESS",
  GET_MAINTENCANCE_BOOKLET_FAILED: "GET_MAINTENCANCE_BOOKLET_FAILED",
  GET_FACTORY_CONFIG: "GET_FACTORY_CONFIG",
  GET_FACTORY_CONFIG_SUCCESS: "GET_FACTORY_CONFIG_SUCCESS",
  GET_FACTORY_CONFIG_FAILED: "GET_FACTORY_CONFIG_FAILED",
  Maintencance_PAGE_DESTORY: "Maintencance_PAGE_DESTORY"
};

module.exports = {
  ...splashActionTypes,
  ...loginActionTypes,
  ...navActionTypes,
  ...mainActionTypes,
  ...receiveCarActionTypes,
  ...autoTypeInputActionTypes,
  ...personCenterActionTypes,
  ...supportActionTypes,
  ...boardActionType,
  ...personCenterActionTypes,
  ...entryReportActionTypes,
  ...carActionTypes,
  ...detectionActionTypes,
  ...opportunityActionTypes,
  ...constructionActionTypes,
  ...manualActionTypes,
  ...constructionActionTypes,
  ...MaintencanceBookletAction,
  ...feedBackActionTypes
};
